# Generated by Django 4.1.2 on 2022-11-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_alter_computer_options_computer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='computer',
            unique_together={('brand', 'model', 'description', 'price')},
        ),
    ]
