# Generated by Django 4.1.2 on 2022-11-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_alter_computer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='computer',
            unique_together={('brand', 'model')},
        ),
    ]
