# Generated by Django 4.1.2 on 2022-11-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_alter_computer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='price',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
