# Generated by Django 4.1.2 on 2022-11-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_computer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='price',
        ),
    ]
