# Generated by Django 4.1.2 on 2022-11-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellphone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellphone',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='cellphone',
            name='description',
            field=models.TextField(),
        ),
    ]
